#!/bin/bash
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

# Update current software and refresh repos.
apt-get update
apt-get -y upgrade


# install packages from "packages" file
cat packages | xargs sudo apt-get install -y
echo "done installing../n"

# install repo for chrome & install
GCPROG='google-chrome'
command -v "$GCPROG" >/dev/null 2>&1 || (
wget -N https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && 
dpkg -i *.deb &&
apt-get -y install google-chrome-stable &&
rm google-chrome-stable_current_amd64.deb )

# create nfs mount for zotac
if [ ! -d "/mnt/share" ]; then
  mkdir -p /mnt/share
fi  
LINE='192.168.0.10:/share      /mnt/share    nfs async,nfsvers=3,actimeo=0,tcp,rsize=32768,wsize=32768    0       0'
grep "$LINE" /etc/fstab >/dev/null  || echo $LINE >> /etc/fstab && mount -a

apt-get -y autoremove
